Repository ssi-dk/diseasy, pull requests merged in 2023-11, with the labels that each got.

#53 Improve and fix printr
  R/0_R6_utils.R
Labels: enhancement, priority

#41 Improved functionality and documentation to DiseasySeason
  R/DiseasySeason.R
  inst/WORDLIST
  man/DiseasySeason.Rd
  tests/testthat/test-DiseasySeason.R
  vignettes/diseasy-season.Rmd
  vignettes/quick-start.Rmd
Labels: documentation, enhancement

#58 test(DiseasyActivity): improve tests
  tests/testthat/test-DiseasyActivity.R
Labels: enhancement

#60 feat(DiseasyActivity): improve type consistency for scenarios
  R/DiseasyActivity.R
Labels: enhancement

#64 docs(DiseasyActivity): add a vignette
  inst/WORDLIST
  vignettes/diseasy-activity.Rmd
Labels: documentation

#57 feat(DiseasyActivity): add activity data
  .Rbuildignore
  R/DiseasyActivity.R
  R/data.R
  README.md
  data-raw/contact_basis.R
  data-raw/dk_activity_units.R
  data/contact_basis.rda
  data/dk_activity_units.rda
  data/dk_reference_scenario.rda
  inst/WORDLIST
  man/contact_basis.Rd
  man/dk_activity_units.Rd
  man/dk_reference_scenario.Rd
  tests/testthat/test-0_examples.R
  tests/testthat/test-0_return.R
  tests/testthat/test-DiseasyActivity.R
Labels: enhancement

#67 feat(contact_basis): improve demography data set
  R/DiseasyActivity.R
  data-raw/contact_basis.R
  data/contact_basis.rda
  man/DiseasyActivity.Rd
  man/contact_basis.Rd
  tests/testthat/test-DiseasyActivity.R
Labels: documentation

#70 feat(DiseasyActivity): ensure consistent age_groups in data
  R/DiseasyActivity.R
Labels: enhancement

#43 Rename aggregation to stratification (fixes #29 and #44)
  R/0_documentation.R
  R/DiseasyBaseModule.R
  R/DiseasyObservables.R
  man/DiseasyObservables.Rd
  tests/testthat/test-0_documentation.R
  tests/testthat/test-DiseasyBaseModule.R
  tests/testthat/test-DiseasyObservables.R
  tests/testthat/test-DiseasySeason.R
Labels: priority

#52 docs(DiseasyBaseModule): add description
  R/DiseasyBaseModule.R
  man/DiseasyBaseModule.Rd
Labels: documentation

#48 Improved documentation to DiseasyObservables
  R/DiseasyBaseModule.R
  R/DiseasyObservables.R
  man/DiseasyBaseModule.Rd
  man/DiseasyObservables.Rd
  vignettes/diseasy-observables.Rmd
Labels: documentation, enhancement

#49 test: ensure no TODOs in code base
  R/0_linters.R
  R/0_non_ascii_linter.R
  R/diseasy-package.R
  man/diseasy_linters.Rd
  tests/testthat/test-0_todo_linter.R
Labels: documentation

#56 Add SSI as copyright holder
  DESCRIPTION
  _pkgdown.yml
Labels: documentation, backlog

#63 feat(DiseasyActivity): improve function signatures for weighing
  R/0_documentation.R
  R/DiseasyActivity.R
  man/DiseasyActivity.Rd
  tests/testthat/test-DiseasyActivity.R
  vignettes/diseasy-activity.Rmd
Labels: enhancement
